language: ruby

rvm:
  - 2.4.0
  - 2.3.3

gemfile:
  - ci/Gemfile.rails-4.2.x
  - ci/Gemfile.rails-5.0.x

env:
  - DB=mysql
  - DB=pg

script: bundle exec rake

before_script:
  - mysql -e 'create database monogamy_test'
  - psql -c 'create database monogamy_test' -U postgres

