language: ruby

rvm:
  - 1.9.3
  - 2.0.0

gemfile:
  - ci/Gemfile.rails-4.0.x
  - ci/Gemfile.rails-3.2.x
  - ci/Gemfile.rails-3.1.x
  - ci/Gemfile.rails-3.0.x

env:
  - DB=sqlite
  - DB=mysql
  - DB=pg

script: bundle exec rake

before_script:
  - mysql -e 'create database monogamy_test'
  - psql -c 'create database monogamy_test' -U postgres

